name: PR - Node CI+CD

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - run: npm install
    - run: npm run build

    - name: Copy to production server
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.DEVHOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.privateKey }}
      with:
        source: "public"
        target: "~/wordpress/wp-content/plugins/nucssa-core/"
        overwrite: true
